### ISSUE TITLE
z7 latest release - 编辑窗口频闪/透明/悬浮图层有误

### ISSUE THREAD

**Issue by RitaQian-westlake** [windingwind/zotero-actions-tags#106]
zotero-tag: 1.0.0-1
Zotero: 7.0.0-beta.39+ecba25be0 (64-bit)
System: Ubuntu 22.04

当在首选项中选择编辑某一action时，弹出的编辑界面会出现如标题所述bug

- 频闪：窗口持续震颤，在拖动时会出现无数窗口叠在一起的效果

- 透明：编辑窗口下层的其它窗口的界面会透过编辑窗口的背景显示出来（不会透过编辑界面里的header, 按钮和文字）；有时切换下层窗口时会保留切换前窗口的图像，比如刚开始编辑窗口的下层窗口是zotero，那么最小化zotero显示github web时，编辑窗口的背景依然是之前与zotero窗口重叠的区域
- 悬浮图层有误：首选项窗口只能出现在编辑窗口上层

因为截图截不到，只能描述一下

**Comment by RitaQian-westlake** [comment]
已测试1.0.0-3，问题未解决

**Comment by windingwind** [comment]
try this: https://askubuntu.com/questions/1279424/firefox-is-rendering-window-and-pages-transparent-and-flickering#:~:text=Problem%3A%20Firefox%20show%20transparent%20window%20when%20set%20gfx.webrender.all,restart%20the%20browser%20then%20all%20back%20to%20normal.

**Comment by wklimowicz** [comment]
Doesn't work for me either, but I think this issue is being tracked in the main zotero github: https://github.com/zotero/zotero/issues/3215
