### ISSUE TITLE
Zotero 6 compatibility?

### ISSUE THREAD

**Issue by huachuman** [windingwind/zotero-actions-tags#116]
Hey will this remain only compatible with Z7 or do you plan on making it for Z6? 

Currently Z7 is not in great usable shape especially since virtually every other plugin isn't compatible. It's also in beta and no official word on a release date.

**Comment by windingwind** [comment]
Z6 has reached the end of its lifespan. V0.3.0 is still accessible to Z6 users, but no more updates.
