### ISSUE TITLE
`require` not defined when using keyboard shortcut

### ISSUE THREAD

**Issue by vancleve** [windingwind/zotero-actions-tags#121]
When running the following code as a script with Event/Action = None,
```
require('ZoteroPane').addAttachmentFromDialog(false, item.id);
```
I get the right attachment dialog box but also get the following errror:
<img width="419" alt="image" src="https://github.com/windingwind/zotero-actions-tags/assets/1442334/05cce94f-bdb0-43c2-8dee-f97afe80739e">
but **only** when I activate the script with the keyboard shortcut:
<img width="581" alt="image" src="https://github.com/windingwind/zotero-actions-tags/assets/1442334/87b04cfa-365b-4155-88ac-c71bc4501294">

**Comment by windingwind** [comment]
What’s the plugin version?

**Comment by windingwind** [comment]
Please update the plugin (there is no auto-update for beta).

**Comment by vancleve** [comment]
I've updated to https://github.com/windingwind/zotero-actions-tags/releases/tag/v1.0.0-8 and the "Script error" is gone. Thanks!

However, now using the keyboard shortcut results in two attach file windows being opened:
<img width="1006" alt="image" src="https://github.com/windingwind/zotero-actions-tags/assets/1442334/ea1ded12-5732-4052-a46a-e7f4377b652f">

**Comment by vancleve** [comment]
I updated to https://github.com/windingwind/zotero-actions-tags/releases/tag/v1.0.0-13 and notice that using the keyboard shortcut now brings up **three** add file dialog windows.

I then restarted Zotero and the shortcut brings up only one window. So I wonder if actually the issue is with the uninstall/upgrade part of the script.

**Comment by windingwind** [comment]
fixed
