### ISSUE TITLE
【bug】zotero 7 最新beta版，无法安装1.0.0-9，显示不兼容

### ISSUE THREAD

**Issue by aiyou9** [windingwind/zotero-actions-tags#123]
zotero 7 最新版
![image](https://github.com/windingwind/zotero-actions-tags/assets/15712822/9eaa82e3-cf98-40ea-ab08-2d949af380ff)
安装插件 [Release 1.0.0-9](https://github.com/windingwind/zotero-actions-tags/releases/tag/v1.0.0-9)
报错
![image](https://github.com/windingwind/zotero-actions-tags/assets/15712822/aedec34f-9d62-4cb5-bef0-6a69c1fa8802)
1.0.0-8 可以成功安装
![image](https://github.com/windingwind/zotero-actions-tags/assets/15712822/ca420adb-c5b7-44a6-abb2-e3dc4e9e32b0)

**Comment by windingwind** [comment]
install latest pre-release

**Comment by aiyou9** [comment]
抱歉，排序问题，我看错了，最新是 11
