### ISSUE TITLE
[FR]增加分组排序分隔符功能

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-actions-tags#138]
增加分组、菜单排序、分隔符功能。

谢谢

**Comment by windingwind** [comment]
不明白什么意思

**Comment by llity** [comment]
对action分组排序分类等

![image](https://github.com/windingwind/zotero-actions-tags/assets/11771112/2997384e-0ede-4f74-b81c-e00a1083af5b)

![image](https://github.com/windingwind/zotero-actions-tags/assets/11771112/4376fa28-2b8e-4cf0-b29a-043b3add838a)

![image](https://github.com/windingwind/zotero-actions-tags/assets/11771112/0a74ee30-5e66-4498-8914-e36bbc921b1b)

**Comment by windingwind** [comment]
谢谢建议，欢迎pr，我没有时间做
