### ISSUE TITLE
插件多个actions行的脚本数据会相互覆盖

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [windingwind/zotero-actions-tags#141]
没摸清具体规律，有时候一个动作运行后，就把临近动作行的脚本数据覆盖了

**Comment by windingwind** [comment]
请提供可复现的操作步骤

**Comment by xjtusjtu** [comment]
> 步骤： 1.添加两行带有不同脚本数据的不同动作 2.将上面一行的动作启用按钮关闭 3.上面一行动作的脚本数据将会自动变成和下面一行动作的脚本数据一模一样

我也遇到了这个问题

**Comment by windingwind** [comment]
我无法复现。可否提供操作录屏
