### ISSUE TITLE
[Feature] Add options for shortcuts often used

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Window 10
- Zotero Version: 7.0.0-beta.43+5e634f57f (64-bit)
- Plugin Version: 1.0.0-15

### Describe the feature request

**Why do you need this feature?**

I would like to get a simple interface to set shortcuts.
This was possible in Zutilo before, but that have not made the plugin compatible with Zotero 7.

### Describe the solution you'd like

**The solution you'd like**

It would nice if a list of standard shortcut could be already listed in the interface, so that the user simply needs to set the shortcut to pre-defined actions? So something similar to what was available in Zutilo.

**Alternatives you've considered**

Some of the shortcuts that were available in Zutilo have already been implemented with a script. So I could already use them.
I understand also that I could ask here for every shortcut that I need, and people could then add it from the [Action Scripts page](https://github.com/windingwind/zotero-actions-tags/discussions/categories/action-scripts).

**Comment by windingwind** [comment]
Isn’t it more convenient if you can record any shortcuts you want?

**Comment by mjthoraval** [comment]
I agree that the plugin you provide is more powerful.
From a basic user's perspective, I just find it a bit complex and scary to copy a script into an interface to define a shortcut.

I would just find it convenient if there was a pre-defined list of shortcuts I could choose from, and then I would just have to choose the shortcut. In a way similar to Zutilo, with the commands listed here:
https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md

I am not sure what would be the best interface to do that.
Maybe just an option to choose from a pre-loaded list of of default possible actions, which would show the capabilities of the plugin? You should only be able to change the shortcut for these pre-loaded actions. If you want to make any changes, you could duplicate it to the actions list where you would be able to modify it for you own needs.

This is of course more aesthetic rather than adding more functionalities. But I would find it easier to use as a basic user.

**Comment by windingwind** [comment]
I would say since the `record` way is what vscode, chrome, and macos use for defining custom shortcuts, there is nothing very wrong with it and thus we have no reason to change it.

**Comment by windingwind** [comment]
Thanks for the suggestion. I will close this thread, but please feel free to reopen it if you want to discuss it further.

**Comment by mjthoraval** [comment]
Here is a relevant thread listing some of the commands that were available in Zutilo, and missed by users:
https://forums.zotero.org/discussion/108833/zutilo-in-zotero-7-which-of-its-functions-are-most-essential
I have started 2 new threads for 2 of these commands that I am using a lot.
I will have a try this way. But it may become difficult to follow if all shortcuts and commands are listed in the [Action Scripts page](https://github.com/windingwind/zotero-actions-tags/discussions/categories/action-scripts).

It gives some idea of the remaining gap between Zutilo and this Actions & Tags plugin:
https://forums.zotero.org/discussion/comment/446787#Comment_446787
