### ISSUE TITLE
[Feature] Relate items from right-click

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version: 1.0.0-17

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to replace the "Relate selected items" function from Zutilo, available from a righ-click on several items:

> Relate items: Set all selected items to be related to each other.

https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md

**Why do you need this feature?**
The Zutilo plugin is not updated for Zotero 7.

### Describe the solution you'd like

**The solution you'd like**
Set all selected items to be related to each other from a right-click on several items.

**Alternatives you've considered**
It is possible to add related items from the Related tab on the right hand side.
But that takes much longer, as you need to search for the items to relate to.

**Comment by windingwind** [comment]
we can have that. i'll make one

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/discussions/164
