### ISSUE TITLE
[Feature] QuickCopy items

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version: 1.0.0-17

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to replace the "QuickCopy items" functions from Zutilo for alternative export translators, available from a righ-click on one or multiple items, but also as a user defined shortcut:

> QuickCopy items: Copy selected items to the clipboard using the "Default output format" specified in the "Export" section of Zotero's preferences. It is also possible to set alternative quick copy items. By default, two such items are enabled, labeled "alt 1" and "alt 2". Additional items can be enabled by changing the extensions.zutilo.copyItems_alt_total preference in the config editor. These items will copy to the clipboard using alternative export translators. To select the translators used by these functions, the corresponding preferences extensions.zutilo.quickcopy_alt1, extensions.zutilo.quickcopy_alt2, etc. must be set in the config editor. Each preference should be set to whatever appears in the config editor for the export.quickCopy.setting preference when the desired translator is set as the "Default output format" in Zotero's preferences. The config editor can be opened from the Advanced pane of Zotero's preferences window.

https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md

**Why do you need this feature?**
The Zutilo plugin is not updated for Zotero 7.

### Describe the solution you'd like

**The solution you'd like**
I would like to be able to a different quick copy of different formats from the righ-click menu and through different user-defined shortcuts. For example: Better BibtTeX and APA 7thedition.

**Alternatives you've considered**
I could change the Quick Copy settings every time, but that is a bit painful.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/discussions/165
