### ISSUE TITLE
[Feature] Abstract Cleaner

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version: 1.0.0-17

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to get a right-click menu option to remove the line endings in the abstract of items.
Something similar to the Abstract Cleaner plugin: https://github.com/dcartertod/zotero-plugins

**Why do you need this feature?**
Some items have abstracts that are wrongly formatted, with many line endings remaining in the abstract.
For some items, no abstract is imported at all. If I copy from Adobe Acrobat, the line endings are also copied. I still need to remove them automatically.
That functionality was available in the Abstract Cleaner plugin. But it is not compatible with Zotero 7.

### Describe the solution you'd like

**The solution you'd like**
I would like to get a menu option "Fix Line Endings in Abstract" available from a righ-click on the item or on the abstract to remove the line endings.

**Alternatives you've considered**
I could use some online tools to automatically remove the line endings, like this one:
https://www.textfixer.com/tools/remove-line-breaks.php
But that would take more time.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/discussions/163
