### ISSUE TITLE
[Feature] Sort actions

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version: 1.0.0-17

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to be able to change the order of the actions available from the righ-click menu.

**Why do you need this feature?**
As I am getting more actions in the menu, it is getting more difficult to find the one I am looking for.

### Describe the solution you'd like

**The solution you'd like**
I would like to be able to move the actions up and down in the list of actions, so that the order is also reflected in the menu.

**Alternatives you've considered**
I could delete them all and add them again manually, but that is clearly not practical.

**Comment by mjthoraval** [comment]
Thank you.
I understand that this update automatically sorts the actions by alphabetic order of the `Menu Label`, is that correct?
I am using emojis in front of each `Menu Label`, so the alphabetic order is not working for me.
Would it still be possible to consider adding a manual ordering option?

**Comment by windingwind** [comment]
You can use like `1👍-xxx`, `2👑-yyy`. Sorting by alphabetic order is the most simple way to implement.

We can have a manual ordering, but I don't think most of our users would actually use that. More options brings more higher learning costs.

**Comment by mjthoraval** [comment]
Ok, thank you

**Comment by mjthoraval** [comment]
Would it be possible to use the `Name` field to sort instead of the `Menu Label` field?
In that way, I can freely reorganize the actions, without affecting the information displayed in the menu.
Using the numbering method would be more intuitive, as it appears on the left side of each action in the settings.

**Comment by mjthoraval** [comment]
Also, for display purposes in the settings, it seems that the table reacts when I click on the title of each column.
So sorting by the first column by default may be possible to do, so that it reflects the order in the menu?

**Comment by windingwind** [comment]
Supported in the latest prerelease.

**Comment by windingwind** [comment]
You'll need to go to settings and change menu -> sort by.

**Comment by mjthoraval** [comment]
Perfect! Thank you very much!
