### ISSUE TITLE
[Feature] tag only the current item

### ISSUE THREAD

**Issue by hasibagen** [windingwind/zotero-actions-tags#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: mac 13.6
- Zotero Version: 6.0.29
- Plugin Version:3 

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

Can this method be employed to tag only the current item? Presently, when alt+1 is associated with tag 1, pressing it results in all new items being tagged with the same tag 1. However, my intention is to tag only the present item with tag 1.

**Why do you need this feature?**
my intention is to tag only the present item with tag 1.

![Snipaste_2023-10-27_16-28-34](https://github.com/windingwind/zotero-actions-tags/assets/12797356/64ba4d69-d4e1-4b8b-a6b0-e8878b532879)

### Describe the solution you'd like

nothing

**Comment by windingwind** [comment]
You choose `add tag when opening item`, so it adds the tag when opening an item.

**Comment by hasibagen** [comment]
> You choose `add tag when opening item`, so it adds the tag when opening an item.

So what should I choose to mark the currently opened item?

**Comment by windingwind** [comment]
`none` and use the shortcut to trigger the add-tag action.
