### ISSUE TITLE
[Feature] 代码导出

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-actions-tags#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macos
- Zotero Version: 7
- Plugin Version:

### Describe the feature request

当使用其他电脑的时候，需要自己电脑这个插件的代码和快捷键的话，一个一个输入太麻烦了，能不能像tampermonkey一样，可以导出或者上传onedrive，随时在其他电脑上使用呢？

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by mjthoraval** [comment]
I am facing the same problem.
I am using Zotero on several computers and it is quite painful to add the actions manually all the time.
I am also worried of losing all my actions if I need to reinstall Zotero from scratch.

I think it would be nice to have a special `ActionsTagsScripts.ats` file format including all the Actions and Tags Scripts.
It would allow you to:
- Export one, several or all your actions to a file.
- Import that file to load the actions scripts into your plugin settings.

It would also speed up the process of adding actions if we could download a `.ats` file from the [Actions Scripts](https://github.com/windingwind/zotero-actions-tags/discussions/categories/action-scripts) page, or even add it directly from the Zotero browser like the `.xpi` files.

Syncing settings between computers has been discussed in the Zotero Forums, but they replied that it is unlikely to happen in the near future.

**Comment by windingwind** [comment]
In progress

**Comment by northword** [comment]
Or, may be [Tara](https://github.com/l0o0/tara) will help you.

**Comment by heyeruoqi** [comment]
> Or, may be [Tara](https://github.com/l0o0/tara) will help you.

but this is not suitable for zotero7

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/releases/tag/v1.0.0-24
