### ISSUE TITLE
[Feature] 功能建议：使用快捷键添加标签时可对《注释》生效

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [windingwind/zotero-actions-tags#178]
### Environment
- OS: win10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version:1.0.0-23

大佬，目前快捷键只能对**条目**添加标签，对**注释**添加标签时无法生效，希望大佬闲暇时可以适配一下注释标签

**Comment by windingwind** [comment]
请问注释指的是，在阅读器中侧边栏选中的注释么

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags#action-settings

支持右键菜单，不支持快捷键。很难判断快捷键的作用范围，到底是当前阅读的条目还是选中的注释条目。
