### ISSUE TITLE
[Feature] Different actions in different locations

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.49+1bb6722c4 (64-bit)
- Plugin Version: 1.0.0-23

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to use different actions in different locations.
For example, right-clicks from:
- Tab title of PDF reader
- Collection
- Annotation in the PDF reader
- Item
- Metadata
- Notes

**Why do you need this feature?**
I would like to use different actions in different locations.
For example:
- A right-click on a collection would let me copy the link to the collection
- A right-clik on an annotation would let me copy the link to that annotation

At the moment, I still see actions like `Related selected items` from the PDF viewer, which is not useful and wasting space.

### Describe the solution you'd like

**The solution you'd like**
It should be possible to write actions for some specific menus.

**Alternatives you've considered**
For example, Zutilo has [Collection menu functions](https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md#collection-menu-functions)

**Comment by windingwind** [comment]
How should we distinguish them? I do not want to add another column in the action editor

**Comment by mjthoraval** [comment]
The easiest way I guess would be to put these options in the `Edit Action` popup window when editing an action. They do not need to appear in the table displayed in the main settings of the plugin in the `Zotero Settings` window.
This could be done for example with tick boxes, either directly at the bottom of the window, or (probably better) inside a popup window, so that it doesn't clutter the interface in the `Edit Action` window.

One alternative would be to move these settings to a separate window for all actions, accessible directly from the main settings page of the pugin. If the user is happy with the default settings, then he does not even need to worry about these advanced settings.
The advantage is that you can handle the settings of all actions at the same time.
However, creating an action for a specific menu becomes more complicated: you need to create the action first, and then go to the menus settings in a different window to specify for which menu it should apply.

[Or it could be both of these first two solutions at the same time.]

Another alternative would be to create a separate list of action for each menu (a separate table in the main settings page).
But this will probably be more complicated, since you would have to duplicate actions that need to be in several menus at the same time.

Here is what the Zutilo settings look like to give some ideas:
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/b2713685-3d78-4231-a326-b1f66475315d)

![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/b5adcfab-c2b5-4be1-915f-064b3c59cc2d)

![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/dbcb1938-50f3-4d96-bc6b-5e963b54b8da)

**Comment by mjthoraval** [comment]
Thank you very much!
