### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ChukieWu** [windingwind/zotero-actions-tags#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.1 (23B74)
- Zotero Version: 7.0.0-beta.50+8239d04d5
- Plugin Version:1.0.0-23

### Describe the bug

(in reading an essay, right in the reading page)When clicking on the tag button of this addon, there exists no content under this tag button 

### Debug Output

1699603572751	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1699603573638	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NotFoundError: Could not get children of file(/Users/chukiewu/Library/Application Support/Zotero/Crash Reports/events) because it does not exist"]
reportErrors@chrome://zotero/content/zoteroPane.js:6019:18
oncommand@chrome://zotero/content/zoteroPane.xhtml:1:18

appName => Zotero, version => 7.0.0-beta.50+8239d04d5, os => macOS 14.1, locale => zh-CN, extensions => Actions and Tags for Zotero (1.0.0-23, extension), Green Frog (0.16.03, extension, disabled), Better Notes for Zotero (1.1.4-28, extension, disabled), Easier Citation (0.4.2, extension, disabled), Awesome GPT (0.3.2, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Crush Reference (0.6.3, extension, disabled), ZotMoov (0.0.2b7, extension, disabled), Ethereal Style (3.2.6, extension, disabled), ZotCard (3.0.3, extension, disabled), Jasminum (1.0.0-7, extension, disabled)

**Comment by windingwind** [comment]
please see readme#action-settings
