### ISSUE TITLE
升级后tag丢失 [Bug] 

### ISSUE THREAD

**Issue by yanyu2015** [windingwind/zotero-actions-tags#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 7.0.0-beta.51+7c5600913 (64-bit)
- Plugin Version: 1.0.0-24

### Describe the bug

由于translate不再支持6.0版本，所以我升级到了zotero7。
打开后，所有的tag都不见了，请问有办法恢复不？那可是大半年手动筛选出来的标签呀。

### Debug Output

1699775864611	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
onStatusChange@chrome://browser/content/browser.js:5565:17
callListeners@chrome://browser/content/tabbrowser.js:902:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:916:22
_callProgressListeners@chrome://browser/content/tabbrowser.js:6356:46
onStatusChange@chrome://browser/content/tabbrowser.js:6813:12

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
onStatusChange@chrome://browser/content/browser.js:5565:17
callListeners@chrome://browser/content/tabbrowser.js:902:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:916:22
_callProgressListeners@chrome://browser/content/tabbrowser.js:6356:46
onStatusChange@chrome://browser/content/tabbrowser.js:6813:12

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

[JavaScript Error: "BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
onStatusChange@chrome://browser/content/browser.js:5565:17
callListeners@chrome://browser/content/tabbrowser.js:902:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:916:22
_callProgressListeners@chrome://browser/content/tabbrowser.js:6356:46
onStatusChange@chrome://browser/content/tabbrowser.js:6813:12

[JavaScript Error: "BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
onStatusChange@chrome://browser/content/browser.js:5565:17
callListeners@chrome://browser/content/tabbrowser.js:902:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:916:22
_callProgressListeners@chrome://browser/content/tabbrowser.js:6356:46
onStatusChange@chrome://browser/content/tabbrowser.js:6813:12

[JavaScript Error: "BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
onStatusChange@chrome://browser/content/browser.js:5565:17
callListeners@chrome://browser/content/tabbrowser.js:902:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:916:22
_callProgressListeners@chrome://browser/content/tabbrowser.js:6356:46
onStatusChange@chrome://browser/content/tabbrowser.js:6813:12

[JavaScript Error: "BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
onStatusChange@chrome://browser/content/browser.js:5565:17
callListeners@chrome://browser/content/tabbrowser.js:902:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:916:22
_callProgressListeners@chrome://browser/content/tabbrowser.js:6356:46
onStatusChange@chrome://browser/content/tabbrowser.js:6813:12

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_showDelayed/this._timer<@chrome://browser/content/browser.js:5756:21

[JavaScript Error: "TypeError: BrowserHandler is undefined" {file: "chrome://browser/content/tabbrowser.js" line: 6866}]
update@chrome://browser/content/tabbrowser.js:6866:9
_hide@chrome://browser/content/browser.js:5767:17
update@chrome://browser/content/browser.js:5727:14
setOverLink@chrome://browser/content/browser.js:5151:23

appName => Zotero, version => 7.0.0-beta.51+7c5600913, os => Windows 10.0 22621, locale => en-US, extensions => Zotero Style (2.6.9, extension), Zotero Debug Bridge (2.0.0, extension), Better BibTex for Zotero (6.7.136, extension), Translate for Zotero (1.1.0-21, extension), Actions and Tags for Zotero (1.0.0-24, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.1, plugin), Widevine Content Decryption Module provided by Google Inc. (null, plugin), ZotFile (5.1.3, extension, disabled), DOI Manager (1.4.2, extension, disabled), Zutilo Utility for Zotero (3.10.0, extension, disabled)

### Anything else?

无

**Comment by windingwind** [comment]
如果你说的是文献条目的tag丢失：升级不影响数据库，数据丢失向zotero forums反馈。
如果你说的是本插件的tag规则丢失：两代插件之间互不兼容，重新创建规则即可。回退到z6仍可查看旧版本规则。

**Comment by yanyu2015** [comment]
我遇到的就是本插件的tag规则丢失了，那么意思是如果我重新创建规则（跟旧版保持一致），我仍然可以查看到原来标记好的文献中对应的本插件的tag嘛？还是说只能退回z6才能看到本插件曾经标记好的那些tag.

**Comment by windingwind** [comment]
文献中的标签不论安装插件与否都存在。插件只是在特定的时候（例如创建文献，打开文献）为他们添加标签。

**Comment by yanyu2015** [comment]
好的，感谢！请先不要关闭该issue，等我找到旧电脑上的规则，原样创建后看看是什么情况，到时候反馈。

**Comment by yanyu2015** [comment]
您好，已经测试过了，不是本插件的问题，然后我发现7还是保留着6的标签的，就是不会在条目最左侧显示那个标签的emoji/颜色了，请问这个是z7z6数据不互通引起的还是z7特色或者bug呢？是特色或bug的话，我去z7那边提问下

**Comment by windingwind** [comment]
可能是您使用了类似style的插件。禁用所有插件，重启zotero试下

**Comment by windingwind** [comment]
由于与插件无关，此处关闭
