### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by wsm6636** [windingwind/zotero-actions-tags#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.0
- Plugin Version: 1.0.0-24

### Describe the feature request

Is it possible to export the configuration with one click? Easy to set up the same on another computer.

**Comment by windingwind** [comment]
Already supported in the latest beta
