### ISSUE TITLE
[Feature] Duplicate action

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.51+7c5600913 (64-bit)
- Plugin Version: 1.0.0-27

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to be able to duplicate an action.

**Why do you need this feature?**
I would like to make 2 versions of https://github.com/windingwind/zotero-actions-tags/discussions/115
- Copy item link
- Copy open-pdf link

### Describe the solution you'd like

**The solution you'd like**
I would like to get a button below the actions to duplicate the selected actions.

**Alternatives you've considered**
I can copy paste manually. But this would take much longer.
I can also export the action and then import it again, which is a bit faster, but still slower than a simple duplicate button.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/releases/tag/v1.0.0-29

**Comment by windingwind** [comment]
<img width="330" alt="image" src="https://github.com/windingwind/zotero-actions-tags/assets/33902321/d4ff4c56-5cbd-4f77-8c4c-d562f53ed5fe">

**Comment by mjthoraval** [comment]
Thank you very much!
