### ISSUE TITLE
[Feature] 增加从剪切版直接导入配置功能

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-actions-tags#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MACOS
- Zotero Version: zotero 7 最新版
- Plugin Version: 最新版

### Describe the feature request

增加从剪切版直接导入配置功能，这样编辑好的脚本很方便就导入了，选择需要每个选项去填写较为繁琐。

谢谢

**Comment by windingwind** [comment]
已有从文件导入。不支持从剪贴板导入
