### ISSUE TITLE
[Bug] 插件无法使用

### ISSUE THREAD

**Issue by yanyu2015** [windingwind/zotero-actions-tags#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 
- Zotero Version: 7.0.0-beta.53+969031a37 (64-bit)
- Plugin Version: 1.0.0-31

### Describe the bug

插件无法生效
具体情况是这样的，我的台式机上目前使用的是zotero 7，但是目前发现插件不能生效。
配置如下：
![image](https://github.com/windingwind/zotero-actions-tags/assets/11142054/6f5b86fb-cada-4edf-9c9b-be4f62399c70)
选中文献条目后
![image](https://github.com/windingwind/zotero-actions-tags/assets/11142054/840ef1c3-be21-4335-a063-7efb11128401)

有点奇怪，是因为不支持emoji么？

### Debug Output

1702630628189	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1702630628632	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "ReferenceError: ztoolkit is not defined" {file: "jar:file:///C:/Users/admin/AppData/Roaming/Zotero/Zotero/Profiles/z56hpzt9.default/extensions/zoteroAddons@ytshen.com.xpi!/chrome/content/scripts/zoteroaddons.js" line: 205}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/admin/AppData/Roaming/Zotero/Zotero/Profiles/z56hpzt9.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 21583}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/admin/AppData/Roaming/Zotero/Zotero/Profiles/z56hpzt9.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 21583}]

[JavaScript Error: "Upload request 3/2XZMW9T2 failed"]

[JavaScript Error: "The group 'Text' has reached its Zotero File Storage quota. Some files were not uploaded. Other Zotero data will continue to sync to the server.

appName => Zotero, version => 7.0.0-beta.53+969031a37, os => Windows 10.0 22621, locale => en-US, extensions => Crush Reference (0.6.4, extension), zotero-inspire-dev (0.3.6, extension), Better BibTex for Zotero (6.7.140, extension), Zotero Debug Bridge (2.0.0, extension), Translate for Zotero (1.1.0-23, extension), Green Frog (0.16.04, extension), Linter for Zotero (1.6.15, extension), Zotero Addons (1.4.0, extension), Actions and Tags for Zotero (1.0.0-31, extension), Zotero Style (2.6.9, extension, disabled), ZotFile (5.1.3, extension, disabled), DOI Manager (1.4.2, extension, disabled), Zutilo Utility for Zotero (3.10.0, extension, disabled)

### Anything else?

无

**Comment by windingwind** [comment]
截图具体动作的设置界面

**Comment by yanyu2015** [comment]
![image](https://github.com/windingwind/zotero-actions-tags/assets/11142054/d84d823a-cb80-4ea6-9202-2490ee0ac0d2)
![image](https://github.com/windingwind/zotero-actions-tags/assets/11142054/13a3d4f2-792b-4493-801b-d292d892db8b)

**Comment by windingwind** [comment]
1. 你的第一个动作，菜单名没写，不会显示在菜单
2. 你的第二个动作，四个显示在菜单中，都没有勾选，自然也不会显示在菜单

**Comment by windingwind** [comment]
如果英文不是很好，可以zotero设置中文界面

**Comment by yanyu2015** [comment]
已经可以正常显示了，感谢您的解答，另外我补充一下，菜单名没写估计是我用emoji代替了，可能插件现在还不支持emoji当菜单名？
然后我还有两个疑问：
-  如图 ![image](https://github.com/windingwind/zotero-actions-tags/assets/11142054/3816670f-7209-41ac-a9af-bd85033f9af3) 这样设置是不是就是当我新建笔记的时候，会创建一个名为“创建笔记”的标签呢？（实际尝试了下发现并没有）或者说要实现这样的效果，应该怎么填写具体的菜单？
- 能不能增加一个script，可以实现之前zutfio中的copy iterm的功能呢？目前是能copy tiem link，但有时候还是希望在外部直接看到自己引用的是哪个文献和对应的年份，不然只有一个链接还是太抽象了点。

**Comment by windingwind** [comment]
> 菜单名没写估计是我用emoji代替了

菜单名是menu label, 和name是两个东西。name不起任何实际效果（除了可以用来给菜单排序）。不设置menu label就是不显示的

> 这样设置是不是就是当我新建笔记的时候，会创建一个名为“创建笔记”的标签呢？（实际尝试了下发现并没有）或者说要实现这样的效果，应该怎么填写具体的菜单？

需要在data一栏填写你要创建的标签名。

> 可以实现之前zutfio中的copy iterm的功能呢？

请搜索了解zotero自带的quick copy功能。
