### ISSUE TITLE
[Bug] subset of keys in shortcut trigger action

### ISSUE THREAD

**Issue by vancleve** [windingwind/zotero-actions-tags#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS 14.2.1
- Zotero Version: 7.0.0-beta.54+6b996d4f9
- Plugin Version: 1.0.0 beta 32

### Describe the bug

I have created an action to show the location of an attached file and give it the short cut `^,⌘,f`:
<img width="1131" alt="image" src="https://github.com/windingwind/zotero-actions-tags/assets/1442334/d4793b83-cbb2-4416-a4a2-cb908acec91e">

Both `^,f` and `⌘,f` trigger the action however. `⌘,f` puts the cursor in the search bar as well as executing the action.

### Debug Output

1704928838962	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1704928839434	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "Style with ID http://www.zotero.org/styles/proceedings-of-the-royal-society-b already loaded from proceedings-of-the-royal-society-b.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

[JavaScript Error: "NotFoundError: Could not get children of file(/Users/vancleve/Library/Application Support/Zotero/Crash Reports/events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.54+6b996d4f9, os => macOS 14.2.1, locale => en-US, extensions => Actions and Tags for Zotero (1.0.0-beta.32, extension), Zutilo Utility for Zotero (3.10.0, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Wandering File (0.2.8, extension, disabled), Crush Reference (0.6.4, extension, disabled), Zotero Addons (1.4.5, extension, disabled), Better BibTex for Zotero (6.7.143, extension, disabled)

(3)(+0014070): itemTree.render(). Displaying Item Tree

(3)(+0000005): Viewing item in pane 0

(4)(+0000003): Registering notifier observer 'itemBox_u2' for [item]

(3)(+0000001): Refreshing item box

(3)(+0001796): [Actions and Tags for Zotero] ⌃,f

(3)(+0000002): [Actions and Tags for Zotero] Script Error {}

(4)(+0000000): Beginning DB transaction 1Q6Mp804

(4)(+0000003): Committed DB transaction 1Q6Mp804

(3)(+0000000): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Shortcut for Show File\n// @author jeremyvancleve\n// @usage Select an item in the library and press the assigned shortcut keys\n\nconst win = require('Zotero').getMainWindow();\nlet attachment = await item.getBestAttachment();\nwin.ZoteroPane.showAttachmentInFilesystem(attachment.id);","shortcut":"⌃,⌘,f","enabled":true,"menu":"Show File","name":"Show File in Finder","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemIDs":[80402]}

(4)(+0000004): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [80402, 'https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.14354']

(4)(+0000002): Beginning DB transaction 8GjVx1uw

(4)(+0000001): Item 80402 has not changed

(3)(+0000000): Revealing /Users/vancleve/science/references/Zotero/storage/FV44KQUA/Chang.Moiron.SánchezTójar.etal_EcolLett.pdf

(4)(+0000005): Committed DB transaction 8GjVx1uw

(3)(+0000001): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Shortcut for Show File\n// @author jeremyvancleve\n// @usage Select an item in the library and press the assigned shortcut keys\n\nconst win = require('Zotero').getMainWindow();\nlet attachment = await item.getBestAttachment();\nwin.ZoteroPane.showAttachmentInFilesystem(attachment.id);","shortcut":"⌃,⌘,f","enabled":true,"menu":"Show File","name":"Show File in Finder","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemID":80402}

(3)(+0000121): Notifier.trigger('open', 'file', [80413]) called [observers: 3]

(3)(+0000000): [Actions and Tags for Zotero] notify open file [80413] undefined

(3)(+0009908): itemTree.render(). Displaying Item Tree

(3)(+0000007): Viewing item in pane 0

(3)(+0000001): Refreshing item box

(3)(+0001621): [Actions and Tags for Zotero] ⌘,f

(3)(+0000003): [Actions and Tags for Zotero] Script Error {}

(4)(+0000000): Beginning DB transaction x6X3MT8t

(4)(+0000002): Committed DB transaction x6X3MT8t

(3)(+0000000): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Shortcut for Show File\n// @author jeremyvancleve\n// @usage Select an item in the library and press the assigned shortcut keys\n\nconst win = require('Zotero').getMainWindow();\nlet attachment = await item.getBestAttachment();\nwin.ZoteroPane.showAttachmentInFilesystem(attachment.id);","shortcut":"⌃,⌘,f","enabled":true,"menu":"Show File","name":"Show File in Finder","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemIDs":[80383]}

(4)(+0000004): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [80383, 'https://doi.org/10.1007/s12080-021-00518-6']

(4)(+0000001): Beginning DB transaction TV3zgQiG

(4)(+0000001): Item 80383 has not changed

(3)(+0000001): Revealing /Users/vancleve/science/references/Zotero/storage/5ALXHZ6U/Reimer.ArroyoEsquivel.Jiang.etal_2021_TheorEcol.pdf

(4)(+0000006): Committed DB transaction TV3zgQiG

(3)(+0000000): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Shortcut for Show File\n// @author jeremyvancleve\n// @usage Select an item in the library and press the assigned shortcut keys\n\nconst win = require('Zotero').getMainWindow();\nlet attachment = await item.getBestAttachment();\nwin.ZoteroPane.showAttachmentInFilesystem(attachment.id);","shortcut":"⌃,⌘,f","enabled":true,"menu":"Show File","name":"Show File in Finder","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemID":80383}

(3)(+0000120): Notifier.trigger('open', 'file', [80384]) called [observers: 3]

(3)(+0000000): [Actions and Tags for Zotero] notify open file [80384] undefined

(3)(+0006292): Getting contents of /Users/vancleve/Library/Application Support/Zotero/Profiles/uqkz16va.default/treePrefs.json

(3)(+0000005): Writing column prefs of length 6087 to file /Users/vancleve/Library/Application Support/Zotero/Profiles/uqkz16va.default/treePrefs.json

**Comment by windingwind** [comment]
fixed
