### ISSUE TITLE
[Bug] Old version 

### ISSUE THREAD

**Issue by purierca** [windingwind/zotero-actions-tags#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11
- Zotero Version: 6.0.30
- Plugin Version: 0.3.0

### Describe the bug

I seem to have an old version of the plugin, as not all features (especially actions) are not available

![image](https://github.com/windingwind/zotero-actions-tags/assets/26160776/241429a4-3c21-4642-a4ee-fc01c5c28af6)

![image](https://github.com/windingwind/zotero-actions-tags/assets/26160776/ef0fc496-1763-4db8-8220-49e03f52ba73)

![image](https://github.com/windingwind/zotero-actions-tags/assets/26160776/5022f965-edbc-4599-9499-6f86182e004e)

### Debug Output

version => 6.0.30, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-GB, appName => Zotero, appVersion => 6.0.30, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.30, extension), Zotero Tag (0.3.0, extension), ZotFile (5.1.2, extension, disabled), Zotero OCR (0.6.0, extension, disabled), Zotero PDF Preview (0.3.7, extension, disabled), Zutilo Utility for Zotero (3.10.0, extension, disabled), Night for Zotero (0.4.23, extension, disabled), Better BibTex for Zotero (6.7.143, extension, disabled), Zotero Better Notes (1.0.4, extension, disabled)

**Comment by windingwind** [comment]
The new features are currently in the beta, which only runs on Zotero 7 beta.
