### ISSUE TITLE
[Bug] The Action and Tag menu items are appended to context menu in Zotero Reader without Trigger Action main menu item

### ISSUE THREAD

**Issue by DonnaCoxBaker** [windingwind/zotero-actions-tags#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 
- Zotero Version: V7 Beta.54 64-bit
- Plugin Version: Beta.32

### Describe the bug

The menus in the main workspace of Zotero display the Actions & Tags menu items as a submenu of an item called "Trigger Action." However, in the Zotero Reader, the context menus of the Annotations have the actions all appended to the main context menu--not as a subset of Trigger Actions: https://drive.google.com/open?id=1rKER2ChdC40sBdd7GttYgYl-9GcrDpRo&usp=drive_fs 

### Debug Output

Open a PDF in Zotero. Create an annotation, then right-click on it--either in the main reader window or in the annotations pane.

**Comment by windingwind** [comment]
because the annotation context menu does not support a sub-menu, we cannot put them under a sub-menu there
