### ISSUE TITLE
[Feature] Key modifier + Click as shortcut

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.56+9edfcba9a (64-bit)
- Plugin Version: 1.0.0-beta.33

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to customize some of the click or double click functions of Zotero with a key modifier.
For example, I would like to be able to `Ctrl` + Click on the URL or DOI field to open it in a browser.
Or `Alt` + Click on an item in My Library to open the URL or DOI in a browser.
See [this discussion](https://forums.zotero.org/discussion/111212/zotero-7-beta-click-on-url-and-doi-in-the-item-pane), and [related one](https://forums.zotero.org/discussion/93419/opening-url-rather-than-pdf-shortcut) mentioned in there.
Or  `Ctrl` + Click on a Tag on the right hand side pane to go to My Library and filter by that tab.
...

**Why do you need this feature?**
This would help me tweak the interface in a convenient way for me when it is not accepted in the main code.

### Describe the solution you'd like

**The solution you'd like**
I would like to add to be able to define a shortcut that includes a Click, like `Ctrl` + Click.

**Alternatives you've considered**
Most of these tweaks probably have a reasonable alternative if they are not accepted in the main code.
And I can configure a right-click menu option if not already available.

### Anything else?

It is just for fine tuning of the interface.
I would understand if that it complicated to implement.
I am just asking to know if that would be possible.

**Comment by windingwind** [comment]
I think it would be very complicated to do key modifier + click. We could hang this request here for now, but no promise

**Comment by mjthoraval** [comment]
Thank you.
