### ISSUE TITLE
[Feature] Add a TRIGGER_EVENT variable

### ISSUE THREAD

**Issue by garth74** [windingwind/zotero-actions-tags#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS 14.2.1 (23C71)
- Zotero Version: 7.0.0-beta.56+9edfcba9a
- Plugin Version: 1.0.0-beta.33

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

Is it possible to include a variable like `trigger` or `event` that indicates what shortcut triggered the script to run? For example, in #245, I separate the collection trigger from the item triggers based on the truthy-ness of `collection`. Although this works, a more straightforward solution would be to have a variable that could more directly be used to filter the script functionality. Admittedly, this would overlap to have scripts for separate triggers.

**Why do you need this feature?**

In several of the community scripts (e.g., #115, #245, #198, etc.), there are situations where some functionality is exposed for certain trigger events. As a result, the trigger event is typically inferred based on variable values such as `items` being null or `item` not being null. Although these methods work in some cases, inferring the trigger event for other contexts is impossible. It also makes extending existing scripts a challenge. 

### Describe the solution you'd like

No solution is necessary; this idea would make some things easier, but I can also see it creating performance issues down the road.

**Comment by windingwind** [comment]
Exposing them to the script makes sense to me!

**Comment by windingwind** [comment]
It‘s available in the latest beta (v1.0.0-beta.34)
