### ISSUE TITLE
[Feature] Automatically Add/Remove one tag when adding/removing another tag

### ISSUE THREAD

**Issue by Cateroo** [windingwind/zotero-actions-tags#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows
- Zotero Version: zotreo 7.0.0-beta.65+b047f3d90; Jurism 6.0.22m4; 
- Plugin Version: Release 0.3.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I have items tagged "Unread" when added. Currently, the only automations are things like adding note/annotation/opening the item - however, that doesn't always mean that I have read the item, it may need to be done over several sittings. I do not want the "unread' tag to be removed until I have actually finished reading the item. 

I have a "Read" tag that I add when I finish reading an item - it would be helpful if there was a way to automatically remove the "Unread" tag when the "read" tag is added. 

**Why do you need this feature?**
Better tagging process for functionality - automate removing specific tags when adding other specific tags to reflect status of item. 

### Describe the solution you'd like

**The solution you'd like**
I would like there to be an option where a specific tag, (e.g. "unread") is automatically removed when I add another specific tag (e.g. "read")

**Alternatives you've considered**
I've tried using existing features (remove tag when adding note/annotation, etc.) but I do not want the "unread" tag to be removed until I have actually finished reading.

**Comment by windingwind** [comment]
That can mean just disabling auto-remove `unread` when closing tabs and using an action to manually add `read` and remove `unread` when you want to.

**Comment by windingwind** [comment]
Yeah. You can create a custom script for that - to add `read` and remove `unread` in one go. Anything that can be scripted should be script!

**Comment by Cateroo** [comment]
but this plugin doesn't have any action corresponding to my finishing of reading an item - it's not adding annotations (that just shows I've started reading it) nor closing an item (which happens again, without finishing reading, and I use an external reader) and I don't create notes in zotero. 

At most it would have to be when I add/modify a particular field entry (Extra/rights) - but even that isn't certain - I'd have to _manually_ make sure I only fill in those fields after I finish reading. 

What I am trying to say is that my finishing reading a text is not something that can be accurately registered by any specific action. I would like for tags to automatically be added with other tags.

**Comment by windingwind** [comment]
> but this plugin doesn't have any action corresponding to my finishing of reading an item

That would be a menu or shortcut, as I said - you should be able to manually trigger an action when you think you finished reading.

I am not saying to do it all automatically - you tell the plugin when you finish, and it can tag/untag for you.

**Comment by Cateroo** [comment]
Ah ok, that seems to work, thanks for clarifying the process 😊
