### ISSUE TITLE
After installing the plug -in, you can't see the top toolbar

### ISSUE THREAD

**Issue by JLChenTop** [windingwind/zotero-actions-tags#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Microsoft Windows 11 家庭中文版
- Zotero Version: 7.0.0-beta.65+b047f3d90 (64-bit)
- Plugin Version:Release 1.0.0-beta.34

### Describe the bug

安装之后顶端工具栏消失不见
安装前
![image](https://github.com/windingwind/zotero-actions-tags/assets/50403350/a0204559-3f17-4e23-af9e-8f5457f68385)
安装之后
![image](https://github.com/windingwind/zotero-actions-tags/assets/50403350/3ed4cd42-2c5d-4213-9958-ec0b6103096c)

### Debug Output

nothing

**Comment by JLChenTop** [comment]
I did encounter this problem. When I disable all plugins, the top toolbar is available; Once I install the plugin, the top toolbar will disappear. Very strange.

**Comment by windingwind** [comment]
**Please make sure you are reporting an issue and following the issue template.**
