### ISSUE TITLE
无法添加空格键 作为快捷键 [Bug] 

### ISSUE THREAD

**Issue by YaoLiMuMu** [windingwind/zotero-actions-tags#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Ubuntu 22.04
- Zotero Version: 7.0.0-beta.67
- Plugin Version: 1.0.0-beta.34

### Describe the bug

在设置界面无法添加空格键作为热键.

### Debug Output

如下图, 输入是空白的
![Screenshot from 2024-03-12 14-49-03](https://github.com/windingwind/zotero-actions-tags/assets/32826811/74686b19-edb9-46bd-99fd-51157e5a9430)

**Comment by windingwind** [comment]
空格不是可见字符，我猜测其实是添加成功了的，只是显示成空白。可以试一下

**Comment by YaoLiMuMu** [comment]
> 空格不是可见字符，我猜测其实是添加成功了的，只是显示成空白。可以试一下

尝试过了, 就是无法设置, 不知道是不是被zotero拦截了

**Comment by windingwind** [comment]
可输入字符在库页面应该会触发quick search，建议最好带控制键

**Comment by windingwind** [comment]
一般设置快捷键时带控制键为好。在z中可输入字符本身有用途。

**Comment by YaoLiMuMu** [comment]
我发现原因可能是按下空格键zotero会触发事件, 这个会导致被选择的条目被撤销(同时右边窗口会显示子集的总条目数量), 这个过程很快, 所以会导致插件获取到的item是空的(即undefined类型), 表征出来用户会觉得空格键是失效的.

**Comment by iiwenwen** [comment]
我也想使用空格作为quicklook的快捷键，目前看来在本插件中是无法实现的，因为我用[zotero-plugin-template](https://github.com/windingwind/zotero-plugin-template)来开发适合zotero7的quicklook插件使用了插件提供的快捷键接口来实现空格作为快捷键，发现一样不能使用。但我使用浏览器原生的addEventListener来设置空格作为快捷键就可以正常打开。

**Comment by windingwind** [comment]
如果不借助本插件提供的快捷键系统，可以使用`Event=Main Window Load`，在窗口加载时`window.addEventListener("keydown", ...)`，可使用浏览器的空格键作为快捷键。

**Comment by YaoLiMuMu** [comment]
@iiwenwen @windingwind ,感谢交流提点, 在`document.getElementById('zotero-items-tree')` 添加`addEventListener`是有效果的,  已经更新 按下空格键进行QuickLook的脚本.请参考:https://github.com/windingwind/zotero-actions-tags/discussions/132#discussioncomment-8904275
