### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by YaoLiMuMu** [windingwind/zotero-actions-tags#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: ubuntu 22.04
- Zotero Version: 7.0.0 beta67
- Plugin Version: 1.0.0-beta.34

### Describe the bug

zotero 7 beta 版本中每次触发执行事件后都会有个弹窗留存在界面上, 尤其是使用内置的非自定义脚本事件, 如增加减少Tag等
这个弹窗一般过了一定时间会自动消失的, 但是会强夺占用窗口和鼠标的focus, 已经影响到后续的常规流畅操作, 弹窗每次都会在相同位置出现(移动了也没有用).

### Debug Output

![image](https://github.com/windingwind/zotero-actions-tags/assets/32826811/a4e5c2fa-a0b4-4600-8b1c-738733f34435)

### Anything else?

这种窗口可能在zotero 6 中也有, 只是z6进度条窗口是在右下角, 并且无法选中和占用鼠标焦点, 所以在zotero6应该影响不大

**Comment by windingwind** [comment]
后续可以加一个选项不显示弹窗；但看起来这样的弹窗位置和形式不太对。可以检查使用zotero connector获取文献的弹窗是否正常，如果不正常请向https://forums.zotero.org/discussions 报告问题

**Comment by JLChenTop** [comment]
![image](https://github.com/windingwind/zotero-actions-tags/assets/50403350/61896484-5d3c-4b30-a633-95e380f446fd)
