### ISSUE TITLE
[Bug] 设置中展示的action的数量不全，只能展示两个Action

### ISSUE THREAD

**Issue by SouthToSouth** [windingwind/zotero-actions-tags#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows10
- Zotero Version: 7.0.0-beta.68+c31a40c74 (64-bit)
- Plugin Version:1.0.0-beta.35

### Describe the bug

条件：
1.拥有三个及以上tag

当我进入Action & Tag 设置界面的时候，只展示了两个action。但其实我有6个action。
当我在进行操作的时候（增加操作，删除操作，复制选中的动作操作，这三个是可行的，编辑选中的操作不行），它会恢复成正确的action
![image](https://github.com/windingwind/zotero-actions-tags/assets/118036951/874a4096-e7a9-4460-8fd1-450513a4f20b)
在action数量正常后，除非重新启动zotero7，这个action数量会是一直都是正常的

还有一个正常显示tag的方法:等待一段时间，关掉设置后重新打开设置，这时候标签也会是正常的

### Debug Output

(3)(+0000021): Columns name width 98.28571428571429

(3)(+0000001): Columns event width 98.28571428571429

(3)(+0000000): Columns operation width 98.28571428571429

(3)(+0000000): Columns data width 98.28571428571429

(3)(+0000000): Columns shortcut width 98.28571428571429

(3)(+0000000): Columns menu width 98.28571428571429

#####  下面是我进行了一个增加action的操作，这之后，action就显示全了
(3)(+0000031): itemTree.render(). Displaying Item Tree

(3)(+0008763): Creating string pref 'extensions.actionsTags.rules.1711257025589-H2GjeTI4'

(3)(+0000020): [Warning] Creating element title with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000001): [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {"0":{},"1":{},"2":{},"3":{},"4":{},"5":{},"6":{},"7":{},"8":{},"9":{},"10":{}}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {"0":{},"1":{},"2":{},"3":{},"4":{},"5":{}}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000714): Starting full-text content processor

(4)(+0000000): Registering notifier observer 'fulltext_Cl' for [sync]
##### 停止一段时间后，action就会显示全部action。我重启了zotero，打开了设置界面，等待一段时间后关掉，再打开设置。这个debuginfo里面省略了: Columns operation width 98.28571428571429这样的和调试信息。这期间好像是zotero它查了一大堆乱七八糟的信息（感觉下面这段debugInfo和插件本身无关）

(3)(+0000075): itemTree.render(). Displaying Item Tree

(3)(+0008146): Starting full-text content processor

(4)(+0000000): Registering notifier observer 'fulltext_Zy' for [sync]

(3)(+0030101): Getting contents of C:\Users\ssss\AppData\Roaming\Zotero\Zotero\Profiles\p1jyy7n2.default\treePrefs.json

(3)(+0000001): Writing column prefs of length 20504 to file C:\Users\ssss\AppData\Roaming\Zotero\Zotero\Profiles\p1jyy7n2.default\treePrefs.json

(3)(+0003033): Checking for unprocessed full-text content

(4)(+0000000): SELECT itemID FROM fulltextItems WHERE synced=2

(3)(+0000001): No unprocessed full-text content found

(3)(+0000000): Unregistering full-text content processor idle observer

(3)(+0000000): Stopping full-text content processor

(3)(+0027858): itemTree.render(). Displaying Item Tree

(3)(+0001672): Columns name width 98.28571428571429

(3)(+0000000): Columns event width 98.28571428571429

(3)(+0000001): Columns operation width 98.28571428571429

(3)(+0000000): Columns data width 98.28571428571429

(3)(+0000000): Columns shortcut width 98.28571428571429

(3)(+0000000): Columns menu width 98.28571428571429

(3)(+0000367): Translate: WARNING: new Zotero.Translate() is deprecated; please don't use this if you don't have to

(3)(+0000001): Translate: All translator detect calls and RPC calls complete:

(3)(+0000000): TEI: 25

(3)(+0000000): Zotero RDF: 25

(3)(+0000000): Bibliontology RDF: 50

(3)(+0000000): MODS: 50

(3)(+0000000): Note HTML: 50

(3)(+0000000): Note Markdown: 50

(3)(+0000000): Simple Evernote Export: 50

(3)(+0000000): BibLaTeX: 100

(3)(+0000000): Bookmarks: 100

(3)(+0000000): CFF: 100

(3)(+0000000): CSL JSON: 100

(3)(+0000000): CSV: 100

(3)(+0000000): Endnote XML: 100

(3)(+0000001): Refer/BibIX: 100

(3)(+0000000): RefWorks Tagged: 100

(3)(+0000000): RIS: 100

(3)(+0000000): Unqualified Dublin Core RDF: 100

(3)(+0000000): Wikidata QuickStatements: 100

(3)(+0000000): Wikipedia Citation Templates: 100

(3)(+0000000): BibTeX: 200

(3)(+0000000): COinS: 310

(4)(+0000009): SELECT key AS domainPath, value AS format FROM settings WHERE setting='quickCopySite' ORDER BY domainPath COLLATE NOCASE

(3)(+0000003): Columns domain width 384

(3)(+0000000): Columns format width 784

(3)(+0000001): Columns locale width 184

(3)(+0000003): Translate: WARNING: new Zotero.Translate() is deprecated; please don't use this if you don't have to

(3)(+0000001): Translate: All translator detect calls and RPC calls complete:

(3)(+0000000): TEI: 25

(3)(+0000000): Zotero RDF: 25

(3)(+0000000): Bibliontology RDF: 50

(3)(+0000000): MODS: 50

(3)(+0000000): Note HTML: 50

(3)(+0000000): Note Markdown: 50

(3)(+0000000): Simple Evernote Export: 50

(3)(+0000000): BibLaTeX: 100

(3)(+0000000): Bookmarks: 100

(3)(+0000001): CFF: 100

(3)(+0000000): CSL JSON: 100

(3)(+0000000): CSV: 100

(3)(+0000000): Endnote XML: 100

(3)(+0000000): Refer/BibIX: 100

(3)(+0000000): RefWorks Tagged: 100

(3)(+0000000): RIS: 100

(3)(+0000000): Unqualified Dublin Core RDF: 100

(3)(+0000000): Wikidata QuickStatements: 100

(3)(+0000000): Wikipedia Citation Templates: 100

(3)(+0000000): BibTeX: 200

(3)(+0000000): COinS: 310

(3)(+0000001): Preferences: menulist attached to extensions.zotero.export.noteQuickCopy.setting has new item matching current pref value '{"mode":"export","id":"asssss7-1sss-4sss-sss6-2sssssss2873","markdownOptions":{"includeAppLinks":true},"htmlOptions":{"includeAppLinks":false}}'

(3)(+0000007): PluginInstaller: fetching addon info

(3)(+0000000): PluginInstaller: addon info fetched

(3)(+0000001): HTTP GET resource://zotero-winword-integration/version.txt

(3)(+0000000): PluginInstaller: fetching addon info

(3)(+0000000): PluginInstaller: addon info fetched

(3)(+0000000): HTTP GET resource://zotero-libreoffice-integration/version.txt

(3)(+0000001): Refreshing styles list

(3)(+0000001): Columns title width 384

(3)(+0000005): HTTP GET resource://zotero-winword-integration/version.txt succeeded with 200

(3)(+0000000): HTTP GET resource://zotero-libreoffice-integration/version.txt succeeded with 200

(4)(+0000570): SELECT COUNT(*) FROM fulltextItems WHERE synced != ? AND ((indexedPages IS NOT NULL AND indexedPages=totalPages) OR (indexedChars IS NOT NULL AND indexedChars=totalChars)) [4]

(4)(+0000001): SELECT COUNT(*) FROM fulltextItems WHERE (indexedPages IS NOT NULL AND indexedPages<totalPages) OR (indexedChars IS NOT NULL AND indexedChars<totalChars)

(4)(+0000001): SELECT COUNT(*) FROM itemAttachments WHERE itemID NOT IN (SELECT itemID FROM fulltextItems WHERE synced != ? AND (indexedPages IS NOT NULL OR indexedChars IS NOT NULL)) [4]

(4)(+0000001): SELECT COUNT(*) FROM fulltextWords

**Comment by windingwind** [comment]
这是已知的zotero的bug，等待zotero修复即可

**Comment by SouthToSouth** [comment]
收到。
