### ISSUE TITLE
[Feature] 请问如何将 zotero 6 中的快捷键设置导入 zotero 7？

### ISSUE THREAD

**Issue by appwcn** [windingwind/zotero-actions-tags#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS
- Zotero Version: both 6 and 7
- Plugin Version: the latest of zotero 6 and zotero 7

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
在 mac 中，其它插件（如 zotcard）在 zotero6 中的设置会传承至 zotero7。但是 tags 不会。
**Why do you need this feature?**
我大约设置了十五条tags的快捷键规则…

### Describe the solution you'd like

**The solution you'd like**
zotero7 继承 zotero6 中的设置。
**Alternatives you've considered**
手动将 zotero6 的设置导入 zotero7。

### Anything else?

深表感谢，希望更多人用上 zotero tags。

**Comment by windingwind** [comment]
由于z6的tag配置方式与z7差异很大，且z7版本不支持原有的一些逻辑规则，因此无法做到继承或导入。需要麻烦您手动重新设置一下
