### ISSUE TITLE
[Feature] Make the Actions table wider

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.73+398454f85 (64-bit)
- Plugin Version: 1.0.0-beta.37

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
The width of the Actions table is too small. I cannot see anything.
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/69b798eb-3f17-445a-be7d-238a39170663)
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/f3babc64-87f2-4ae8-9810-ff261c4bd30c)

**Why do you need this feature?**
I need to be able to see something in the table.

### Describe the solution you'd like

**The solution you'd like**
I would like to get a table that can be expanded, same as in the Cite section of the Settings (or better):
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/bcdee8b1-d1ad-48c7-bd4a-40dea47a9ef7)
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/e33bdae6-3bab-448f-9b94-37b000a94395)

**Alternatives you've considered**
No.

**Comment by mjthoraval** [comment]
And some other problems in the UI:
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/b117536b-db01-4adf-be72-72ec8c33801e)

Cannot reduce the width of the Enabled column:
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/c8a15028-0fb9-4283-8205-ab942c305568)

**Comment by windingwind** [comment]
Thanks for the report. Yes, the UI needs to be tuned for the new Zotero 7

**Comment by mjthoraval** [comment]
Thank you very much for fixing the width of the table.
The icons and the data box still need to be fixed. Should I open a new issue for these?
- Off-center icons:
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/c5485250-8650-45ea-91eb-fe7e3d6a7e68)
- Data box:
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/7554005f-789e-4493-9b3d-e46d7f299c70)

**Comment by windingwind** [comment]
Thanks for reminding me. Will fix.
