### ISSUE TITLE
[Feature] Correct dark mode text in the Edit Action window

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.73+398454f85 (64-bit)
- Plugin Version: 1.0.0-beta.37

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
The dropdown menus in the Edit Action window are not compatible with dark mode:
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/807bfcae-120c-4f9a-97a0-68d162fd5c16)

**Comment by quarkquartet** [comment]
Same here. Any thoughts?

**Comment by mjthoraval** [comment]
The plugin is quite difficult to use in dark mode because of this:

![Image](https://github.com/user-attachments/assets/cc39ec19-d191-455d-81dd-a63468cd3adb)

It is not possible for me to reopen the issue. Should I open another one again?

**Comment by windingwind** [comment]
Sorry forgot to update this.

**Comment by windingwind** [comment]
Should be fixed in v2.1.1

**Comment by mjthoraval** [comment]
Thank you!

![Image](https://github.com/user-attachments/assets/1dd04966-5cff-42ca-9fc4-a0249560bf36)
