### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cdewittmd** [windingwind/zotero-actions-tags#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

paste tags was previously working, but stopped working this week and now get error: Actions & Tags
Script Error:
Cc['@mozilla.org/embedcomp/prompt-service;1'] is undefined

### Debug Output

1713380406125	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

appName => Zotero, version => 7.0.0-beta.74+2e8073ab9, os => macOS 14.4.1, locale => en-US, extensions => Actions and Tags for Zotero (1.0.0-beta.38, extension), Zutilo Utility for Zotero (3.10.0, extension, disabled), Open PDF for Zotero (0.0.11, extension, disabled)

(3)(+0060576): itemTree.render(). Displaying Item Tree

(3)(+0000986): Getting contents of /Users/chris/Library/Application Support/Zotero/Profiles/39yva2i9.default/treePrefs.json

(3)(+0000002): Writing column prefs of length 4350 to file /Users/chris/Library/Application Support/Zotero/Profiles/39yva2i9.default/treePrefs.json

(3)(+0001347): itemTree.render(). Displaying Item Tree

(3)(+0005653): itemTree.render(). Displaying Item Tree

(3)(+0000002): Viewing item

(3)(+0000003): Refreshing item box

(3)(+0000022): Switching lastCreatorFieldMode to 0

(3)(+0000006): Setting mode to 'edit'

(3)(+0000000): Reloading tags box

(4)(+0001624): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20606, '']

(4)(+0000020): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20606, '']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20606, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20606, '']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20606, '']

(4)(+0003817): Beginning DB transaction AKYO5u3m

(4)(+0000001): Committed DB transaction AKYO5u3m

(3)(+0000000): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Copy tags. \n// Codes from Zutilo.\n// 获取条目tags，并存入剪贴板\nvar tagsArray = [];\nvar items = Zotero.getActiveZoteroPane().getSelectedItems();\nfor (let item of items) {\n\n if (item.isRegularItem() && !item.isCollection()) {\n\n var tempTags = item.getTags();\n var arrayStr = '';\n for (var j = 0; j < tempTags.length; j++) {\n arrayStr = '\\n' + tagsArray.join('\\n') + '\\n';\n\n let tag\n tag = tempTags[j].tag\n\n if (arrayStr.indexOf('\\n' + tag + '\\n') == -1) {\n tagsArray.push(tag);\n }\n }\n }\n\n}\nvar clipboardText = tagsArray.join('\\r\\n');\ncopyToClipboard(clipboardText)\nreturn \"Tags copied.\"\n\n// 复制到剪贴板函数\nfunction copyToClipboard(clipboardText) {\n var document = require('window').document; // Zotero Actions & Tags需要\n if (clipboardText) {\n const gClipboardHelper =\n Components.classes['@mozilla.org/widget/clipboardhelper;1']\n .getService(Components.interfaces.nsIClipboardHelper);\n gClipboardHelper.copyString(clipboardText, document);\n } else {\n var prompts = Components.\n classes['@mozilla.org/embedcomp/prompt-service;1'].\n getService(Components.interfaces.nsIPromptService);\n var title = 'Invalid copy selection';\n var text = 'No valid items selected for copying. The clipboard has not been modified.';\n prompts.alert(null, title, text)\n }\n}","shortcut":"","enabled":true,"menu":"Copy Tags","name":"Copy Tags","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemIDs":[20606],"triggerType":"menu"}

(4)(+0000007): Beginning DB transaction WMKH67R7

(4)(+0000001): Item 20606 has not changed

(4)(+0000000): Committed DB transaction WMKH67R7

(3)(+0000000): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Copy tags. \n// Codes from Zutilo.\n// 获取条目tags，并存入剪贴板\nvar tagsArray = [];\nvar items = Zotero.getActiveZoteroPane().getSelectedItems();\nfor (let item of items) {\n\n if (item.isRegularItem() && !item.isCollection()) {\n\n var tempTags = item.getTags();\n var arrayStr = '';\n for (var j = 0; j < tempTags.length; j++) {\n arrayStr = '\\n' + tagsArray.join('\\n') + '\\n';\n\n let tag\n tag = tempTags[j].tag\n\n if (arrayStr.indexOf('\\n' + tag + '\\n') == -1) {\n tagsArray.push(tag);\n }\n }\n }\n\n}\nvar clipboardText = tagsArray.join('\\r\\n');\ncopyToClipboard(clipboardText)\nreturn \"Tags copied.\"\n\n// 复制到剪贴板函数\nfunction copyToClipboard(clipboardText) {\n var document = require('window').document; // Zotero Actions & Tags需要\n if (clipboardText) {\n const gClipboardHelper =\n Components.classes['@mozilla.org/widget/clipboardhelper;1']\n .getService(Components.interfaces.nsIClipboardHelper);\n gClipboardHelper.copyString(clipboardText, document);\n } else {\n var prompts = Components.\n classes['@mozilla.org/embedcomp/prompt-service;1'].\n getService(Components.interfaces.nsIPromptService);\n var title = 'Invalid copy selection';\n var text = 'No valid items selected for copying. The clipboard has not been modified.';\n prompts.alert(null, title, text)\n }\n}","shortcut":"","enabled":true,"menu":"Copy Tags","name":"Copy Tags","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemID":20606,"triggerType":"menu"}

(3)(+0001866): itemTree.render(). Displaying Item Tree

(3)(+0000006): Viewing item

(3)(+0000003): Refreshing item box

(3)(+0000021): Switching lastCreatorFieldMode to 0

(3)(+0000005): Switching lastCreatorFieldMode to 0

(3)(+0000005): Setting mode to 'edit'

(3)(+0000001): Reloading tags box

(4)(+0000858): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000010): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0004502): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000023): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [20609, '']

(3)(+0003046): [Actions and Tags for Zotero] Script Error {}

(4)(+0000000): Beginning DB transaction gBqXFxFy

(4)(+0000001): Committed DB transaction gBqXFxFy

(3)(+0000001): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Paste tags\n// Codes from Zutilo.\n// 从剪贴板获取tags\nvar clipboardText = getFromClipboard().trim()\nif (!clipboardText) {\n return false;\n}\n// 拆分\nvar tagArray = clipboardText.split(/\\r\\n?|\\n/)\ntagArray = tagArray.map(function (val) { return val.trim() });\ntagArray = tagArray.filter(Boolean)\n// 添加tags\nvar items = Zotero.getActiveZoteroPane().getSelectedItems();\nfor (let item of items) {\n if (item.isRegularItem() && !item.isCollection()) {\n for (let tag of tagArray) {\n item.addTag(tag)\n }\n item.saveTx()\n }\n\n}\nreturn \"Tags pasted.\"\n\n\n// 从剪贴板获取数据函数\nfunction getFromClipboard(silent) {\n var trans = Components.classes['@mozilla.org/widget/transferable;1'].\n createInstance(Components.interfaces.nsITransferable);\n // if ('init' in trans) {\n // trans.init(window.QueryInterface(Ci.nsIInterfaceRequestor).\n // getInterface(Ci.nsIWebNavigation));\n // }\n trans.addDataFlavor('text/unicode');\n\n Services.clipboard.getData(trans, Services.clipboard.kGlobalClipboard);\n\n var str = {}\n var strLength = {}\n\n try {\n trans.getTransferData('text/unicode', str, strLength);\n } catch (err) {\n if (!silent) {\n var prompts = Cc['@mozilla.org/embedcomp/prompt-service;1'].\n getService(Components.interfaces.nsIPromptService);\n prompts.alert(\n null,\n 'clipboard error',\n 'attempted to copy text from the clipboard, but no valid text was found.'\n )\n }\n return '';\n }\n\n var pasteText\n if (str) {\n pasteText = str.value.\n QueryInterface(Components.interfaces.nsISupportsString).data;\n } else {\n pasteText = '';\n }\n\n return pasteText;\n};","shortcut":"","enabled":true,"menu":"Paste Tags","name":"Paste Tags","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemIDs":[20609],"triggerType":"menu"}

(3)(+0000002): [Actions and Tags for Zotero] Script Error {}

(4)(+0000001): Beginning DB transaction Z8rJNUaA

(4)(+0000000): Item 20609 has not changed

(4)(+0000000): Committed DB transaction Z8rJNUaA

(3)(+0000000): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Paste tags\n// Codes from Zutilo.\n// 从剪贴板获取tags\nvar clipboardText = getFromClipboard().trim()\nif (!clipboardText) {\n return false;\n}\n// 拆分\nvar tagArray = clipboardText.split(/\\r\\n?|\\n/)\ntagArray = tagArray.map(function (val) { return val.trim() });\ntagArray = tagArray.filter(Boolean)\n// 添加tags\nvar items = Zotero.getActiveZoteroPane().getSelectedItems();\nfor (let item of items) {\n if (item.isRegularItem() && !item.isCollection()) {\n for (let tag of tagArray) {\n item.addTag(tag)\n }\n item.saveTx()\n }\n\n}\nreturn \"Tags pasted.\"\n\n\n// 从剪贴板获取数据函数\nfunction getFromClipboard(silent) {\n var trans = Components.classes['@mozilla.org/widget/transferable;1'].\n createInstance(Components.interfaces.nsITransferable);\n // if ('init' in trans) {\n // trans.init(window.QueryInterface(Ci.nsIInterfaceRequestor).\n // getInterface(Ci.nsIWebNavigation));\n // }\n trans.addDataFlavor('text/unicode');\n\n Services.clipboard.getData(trans, Services.clipboard.kGlobalClipboard);\n\n var str = {}\n var strLength = {}\n\n try {\n trans.getTransferData('text/unicode', str, strLength);\n } catch (err) {\n if (!silent) {\n var prompts = Cc['@mozilla.org/embedcomp/prompt-service;1'].\n getService(Components.interfaces.nsIPromptService);\n prompts.alert(\n null,\n 'clipboard error',\n 'attempted to copy text from the clipboard, but no valid text was found.'\n )\n }\n return '';\n }\n\n var pasteText\n if (str) {\n pasteText = str.value.\n QueryInterface(Components.interfaces.nsISupportsString).data;\n } else {\n pasteText = '';\n }\n\n return pasteText;\n};","shortcut":"","enabled":true,"menu":"Paste Tags","name":"Paste Tags","showInMenu":{"item":true,"collection":true,"tools":true,"reader":true,"readerAnnotation":true}} {"itemID":20609,"triggerType":"menu"}

(3)(+0002164): [Actions and Tags for Zotero] undefined

(3)(+0148258): itemTree.changeCollectionTreeRow(): C116

(3)(+0000001): itemTree.render(). Displaying Item Pane Message

(3)(+0000002): Refreshing items list for item-tree-main-default

(4)(+0000028): CREATE TEMPORARY TABLE tmpSearchResults_pfGfEdFH AS SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND (itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL)) AND (itemID IN (SELECT itemID FROM items WHERE libraryID=?)) AND itemID IN (SELECT itemID FROM collectionItems WHERE (collectionID IN (116, 709, 711))) [1]

(4)(+0000011): CREATE INDEX tmpSearchResults_pfGfEdFH_itemID ON tmpSearchResults_pfGfEdFH(itemID)

(4)(+0000001): SELECT GROUP_CONCAT(itemID) FROM items WHERE itemID IN (SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND (itemID IN (SELECT itemID FROM items WHERE libraryID=?))) AND (itemID IN (SELECT itemID FROM tmpSearchResults_pfGfEdFH) OR itemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_pfGfEdFH)) OR itemID IN (SELECT itemID FROM itemNotes WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_pfGfEdFH))) [1]

(4)(+0000012): DROP TABLE IF EXISTS tmpSearchResults_pfGfEdFH

(3)(+0000001): Refreshed open parents in 0 ms

(3)(+0000000): Updating tag selector from current view

(3)(+0000000): Creating tmpSearchResults_xn9HhzBm with 30 items

(3)(+0000001): itemTree.render(). Displaying Item Tree

(3)(+0000005): itemTree.render(). Displaying Item Tree

(3)(+0000016): itemTree.render(). Displaying Item Tree

(4)(+0000003): CREATE UNIQUE INDEX tmpSearchResults_xn9HhzBm_itemID ON tmpSearchResults_xn9HhzBm(itemID)

(4)(+0000001): SELECT DISTINCT tagID || ':' || type FROM itemTags JOIN tags USING (tagID) WHERE 1 AND itemID IN (SELECT itemID FROM tmpSearchResults_xn9HhzBm UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_xn9HhzBm)) ORDER BY name COLLATE NOCASE

(3)(+0000000): Sorted tags in 0 ms

(3)(+0000000): Rendering tag selector

(3)(+0000001): Rendering tag list

(3)(+0000003): Tag selector updated

(4)(+0000136): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [19646, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [17103, 'https://linkinghub.elsevier.com/retrieve/pii/S2589537020300584']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [15578, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [14566, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [14008, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12684, '']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [2367, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [2143, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1375, '']

(3)(+0000365): itemTree.render(). Displaying Item Tree

**Comment by windingwind** [comment]
Any issue related to a specific custom action should be reported to the author. Closed.
