### ISSUE TITLE
Problem Downloading Zotero Actions Tags [Bug] 

### ISSUE THREAD

**Issue by antsmer** [windingwind/zotero-actions-tags#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows
- Zotero Version: 6.0.36
- Plugin Version: 1.0.0

### Describe the bug

When I try to download the plugin xpi file version 1.0.0-XX (I've tried multiple) and add it into zotero, I get the following error: "The add-on "%S" could not be installed. It may be incompatible with this version of Zotero."

Thanks for the great plug in btw!

### Debug Output

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://lanah%40ualberta%2Eca:****@app.koofr.net/dav/Koofr/zotero/
Line Number 1, Column 1:" {file: "https://lanah%40ualberta%2Eca:****@app.koofr.net/dav/Koofr/zotero/" line: 1}]

[JavaScript Error: "1714166889202	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1714166889202	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

version => 6.0.36, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.36, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.36, extension), Zotero Word for Windows Integration (6.0.4.SA.6.0.36, extension), Notero (0.5.15, extension, disabled), Zotero Better Notes (1.0.4, extension, disabled)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags?tab=readme-ov-file#-install
