### ISSUE TITLE
[Bug] emjio 添加标签后，按快捷键不能删除

### ISSUE THREAD

**Issue by Hisschao** [windingwind/zotero-actions-tags#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:
zotero 7

### Describe the bug

alt添加标签 emjio 我使用快捷键ctrl删除标签并没有删除掉

### Debug Output

alt添加标签 emjio 我使用快捷键ctrl删除标签并没有删除掉

**Comment by windingwind** [comment]
请不要设置单纯的功能键为快捷键。本身有作用的按键组合可能不会正常触发动作。
