### ISSUE TITLE
[Feature] Do not run "Add tag" when group member add items. 

### ISSUE THREAD

**Issue by HoollyFox** [windingwind/zotero-actions-tags#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS 14.2.1
- Zotero Version:  7.0.0-beta.68+c31a40c74
- Plugin Version: beta.39

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
When a group member adds an item, the plugin **[zotero-actions-tags](https://github.com/windingwind/zotero-actions-tags)** will add tags.

### Describe the solution you'd like

**The solution you'd like**
Add an option to toggle it or not. An optional description like:
"[ ] Run for group item" 

**Alternatives you've considered**
Or default not run the plugin if group item added.

**Comment by ronny3** [comment]
I was just looking for this same thing! Option to not run on group libraries.
