### ISSUE TITLE
[Bug] show file被归为open file event进而触发自定义脚本

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-actions-tags#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win11
- Zotero Version: beta7.79
- Plugin Version: 1.0.0-beta.39

### Describe the bug

我自定义的添加/reading标签的脚本，触发事件选择的插件预置的open file，然而今天发现在parent item或者attachment邮件show file，也会触发改脚本。
猜测是因为插件本身将show file归为了open file事件的一种？然而是否应该将open file限定为open in new tab或者open in new window（或者再加上外部程序打开），而不应该包含show file呢。

### Debug Output

none

**Comment by windingwind** [comment]
show file 本身会触发open file的notifier，因此被插件认为是打开文件。由于无法检测open in new window，因此只能检测open file。谢谢建议
