### ISSUE TITLE
[Bug] Does not work well with dark mode

### ISSUE THREAD

**Issue by quarkquartet** [windingwind/zotero-actions-tags#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.5
- Zotero Version: Zotero 7.0.0-beta.81+721f54fe4
- Plugin Version: 1.0.0-beta.39

### Describe the bug

Same as https://github.com/windingwind/zotero-actions-tags/issues/312 but it seems it's closed without any reply and update.

On dark mode, the 'action' and 'event' setting panel is white and not visible. See the following image.

<img width="799" alt="image" src="https://github.com/windingwind/zotero-actions-tags/assets/26316540/451e6e0c-a77e-4c5c-a807-f6d1b0a84cf4">

### Debug Output

1716923562780	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

1716923563606	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "uncaught exception: undefined"]

appName => Zotero, version => 7.0.0-beta.81+721f54fe4, os => macOS 14.5, locale => en-US, extensions => Actions and Tags for Zotero (1.0.0-beta.39, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Better BibTex for Zotero (6.7.202, extension, disabled), zotero-inspire (0.3.8, extension, disabled), Zotero Attanger (1.2.2, extension, disabled), MarkDB-Connect (0.1.0, extension, disabled)

**Comment by GCS-ZHN** [comment]
me too~, macOS Sonoma 14.4.1, Zotero 7
