### ISSUE TITLE
[Bug] Trigger Other Actions doesnot work for certain actions

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-actions-tags#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win11
- Zotero Version: 7.0.0-beta.84+71f83c0a3 (64-bit)
- Plugin Version: 1.0.0-beta.42

### Describe the bug

I add two actions in the Data (without quotes) but nothing happens when I trigger this action. Same as [FeralFlora](https://github.com/FeralFlora)‘s description even using the latest plugin. https://github.com/windingwind/zotero-actions-tags/discussions/169#discussioncomment-9690342
However, at least, the Format Chinese Annotations action can be triggered by the parent action.

### Debug Output

(3)(+0000001): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"/**\n * Toggle Left Pane\n * @author [MuiseDestiny](https://github.com/MuiseDestiny), windingwind\n * @usage Assign a shortcut\n * @link https://github.com/windingwind/zotero-actions-tags/discussions/169\n * @see https://github.com/windingwind/zotero-actions-tags/discussions/169\n */\nconst Zotero = require(\"Zotero\");\nconst Zotero_Tabs = require(\"Zotero_Tabs\");\nconst document = require(\"document\");\n\nif (item) {\n return;\n}\n\nif (Zotero_Tabs.selectedType === \"library\") {\n const splitter = document.querySelector(\"#zotero-collections-splitter\");\n if (splitter.getAttribute(\"state\") == \"collapsed\") {\n splitter.setAttribute(\"state\", \"\");\n return;\n } else {\n splitter.setAttribute(\"state\", \"collapsed\");\n return;\n }\n} else {\n Zotero.Reader.getByTabID(\n Zotero_Tabs.selectedID\n )._internalReader.toggleSidebar();\n return;\n}","shortcut":"Ctrl,Alt,4","enabled":true,"menu":"","name":"Toggle Left Pane","showInMenu":{"item":false,"collection":false,"tools":false,"reader":false,"readerAnnotation":false}} {"itemID":7199,"triggerType":"shortcut"}

BTW, The Debug output is the same as the output when trigger the origin Toggle Left Pane action.

**Comment by windingwind** [comment]
Could you please take a screenshot of your actions list?

**Comment by windingwind** [comment]
yes, please make sure you can run the sub-actions separately.

**Comment by ramonmi** [comment]
> yes, please make sure you can run the sub-actions separately.

Yes, I can confirm that they can all run independently. I have been using them for a long time.
