### ISSUE TITLE
[Feature] 添加 extraField.ts 到插件中

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-actions-tags#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

添加下面这个模块到插件中，以方便调用，对 extra字段进行修改

[zotero-plugin-toolkit/src/tools/extraField.ts at master · windingwind/zotero-plugin-toolkit](https://github.com/windingwind/zotero-plugin-toolkit/blob/master/src/tools/extraField.ts)

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
`Zotero.ActionsTags.api.utils.ExtraField` is now supported.
