### ISSUE TITLE
cannot install plugin [Bug] 

### ISSUE THREAD

**Issue by daniu-de** [windingwind/zotero-actions-tags#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 10 22H2
- Zotero Version: 7.0.0-beta.105+c5c613c82 (64-bit)
- Plugin Version: 0.3.0

### Describe the bug

When trying to install I get an error message (translated from my language): "the extension <FILEPATH AND NAME> could not be installed. Possibly it is incompatible with this version of zotero"

### Debug Output

1721721660685	addons.xpi	WARN	Checking <userfolder>\AppData\Local\Zotero7\distribution\extensions for addons
PAC file installed from http://127.0.0.1:9000/systemproxy-3d88f5d8.pac
[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]
1721721663508	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled
[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]
[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]
1721721684328	addons.xpi	WARN	Invalid XPI: Error: File <userfolder>\Downloads\zotero-tag.xpi does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:685:11) JS Stack trace: loadManifest@XPIInstall.jsm:685:11
appName => Zotero, version => 7.0.0-beta.105+c5c613c82, os => Windows 10.0 19045, locale => de, extensions => OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin)
(3)(+0009703): Scheduling next feed update
(4)(+0000000): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1
(3)(+0000000): No feeds with auto-update
(4)(+0000000): SELECT libraryID AS id FROM feeds WHERE refreshInterval IS NOT NULL AND ( lastCheck IS NULL OR (julianday(lastCheck, 'utc') + (refreshInterval/1440.0) - julianday('now', 'utc')) <= 0 )
(3)(+0000001): Running update for feeds:
(3)(+0000000): All feed updates done
(3)(+0000000): Scheduling next feed update
(4)(+0000000): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1
(3)(+0000000): No feeds with auto-update
(4)(+0001109): SELECT COUNT(*) FROM settings WHERE setting='mImport' AND key='cleanup'
(3)(+0000874): itemTree.render(). Displaying Item Tree
(3)(+0001476): itemTree.render(). Displaying Item Tree
(3)(+0009115): Alert: Die Erweiterung "<userfolder>\Downloads\zotero-tag.xpi" konnte nicht installiert werden. Sie ist eventuell inkompatibel mit dieser Version von Zotero.
(3)(+0008533): Starting full-text content processor
(4)(+0000000): Registering notifier observer 'fulltext_TA' for [sync]
(3)(+0030692): Getting contents of <userfolder>\AppData\Roaming\Zotero\Zotero\Profiles\r0zxovmf.default\treePrefs.json
(3)(+0000000): Writing column prefs of length 6569 to file <userfolder>\AppData\Roaming\Zotero\Zotero\Profiles\r0zxovmf.default\treePrefs.json

**Comment by daniu-de** [comment]
Hi,
no idea why but now I could install the plugin - maybe because I updated zotero to the latest (112) beta version
strangely after installation the plugin was set to chinese - after resetting my language in Zotero itsself it worked properly
Thanks a lot

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags?tab=readme-ov-file#-install
