### ISSUE TITLE
[Bug] Zotero_Tabs not support in script

### ISSUE THREAD

**Issue by saccohuo** [windingwind/zotero-actions-tags#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.113+151218e4d (64-bit)
- Plugin Version: 1.0.0-beta.44

### Describe the bug

`Zotero_Tabs` api not support in script. Is there some limitation on the api?
I am writing a script to get all annotations in the current pdf Reader tab. It works on Tools menu, but not works on Reader menu.

### Debug Output

The same code in `Run Javascript`  and `Actions&Tags script` give the different result.

`Run Javascript` code:
```
Zotero.debug("test: Zotero.Zotero_Tabs is " + typeof Zotero.Zotero_Tabs);
Zotero.debug("test: Zotero_Tabs is " + typeof Zotero_Tabs);
```
`Run Javascript` output:
```
(3)(+0015537): test: Zotero.Zotero_Tabs is undefined

(3)(+0000000): test: Zotero_Tabs is object
```

`Actions&Tags script` code::
```
Zotero.debug("test: Zotero.Zotero_Tabs is " + typeof Zotero.Zotero_Tabs);
Zotero.debug("test: Zotero_Tabs is " + typeof Zotero_Tabs);
```
`Actions&Tags script` output:
```
(3)(+0000001): test: Zotero.Zotero_Tabs is undefined

(3)(+0000000): test: Zotero_Tabs is undefined
```

### Anything else?

![image](https://github.com/user-attachments/assets/19a7c530-62c6-4344-bfa5-1a01baec60e2)
![image](https://github.com/user-attachments/assets/7f2fc3ba-babe-4b17-b1f7-d4b0c2f7b3fd)

**Comment by windingwind** [comment]
See https://github.com/windingwind/zotero-actions-tags?tab=readme-ov-file#custom-script -> `require`
