### ISSUE TITLE
[Bug] Unable to install extension

### ISSUE THREAD

**Issue by rwarkotsch** [windingwind/zotero-actions-tags#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 10
- Zotero Version: 6.0.26
- Plugin Version: 2.0.0

### Describe the bug

When trying to install the extension following the instructions I get the following error: 

"Die Erweiterung "%S" konnte nicht installiert werden. Sie ist eventuell inkompatibel mit dieser Version von Zotero." (German)
"The extension "%S" could not be installed. It might be incompatible with this version of Zotero." (own translation)

### Debug Output

[JavaScript Error: "1723627559802	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1723627559803	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

version => 6.0.26, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => de, appName => Zotero, appVersion => 6.0.26, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.26, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.26, extension), Zotero OCR (0.7.3, extension, disabled), Better BibTex for Zotero (6.7.221, extension, disabled), Zotero Citation Counts Manager (1.3.0, extension, disabled)

(3)(+0030775): Starting full-text content processor

### Anything else?

I have seen, there has been a similar issue marked as invalid referring to the installation instructions. However, as I followed these instructions, the bug pertains. Maybe the extension is not compatible with Zotero 6? In that case, this information should be added to the readme.

**Comment by windingwind** [comment]
update to Zotero 7, or use an old version of the plugin (<1.0.0)

**Comment by rwarkotsch** [comment]
Thanks!
