### ISSUE TITLE
[Feature] Hope to support space as a shortcut key

### ISSUE THREAD

**Issue by yeyun1999** [windingwind/zotero-actions-tags#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

I wrote a script to use an external program (quicklook) to open PDF. In Windows, the shortcut key for quicklook is space. I want to keep it the same in Zotero as in Windows, but the plugin cannot set space as the shortcut key.

### Describe the solution you'd like

**support space as a shortcut key**

**Comment by windingwind** [comment]
Zotero has a feature called search-as-you-type (https://www.zotero.org/support/searching#speeding_up_quick_searches), which holds all visible character keys, i.e. A-Z, numbers, symbols, including space. We don't want to break this Zotero feature.

Zotero 7 already provides an in-app preview in the right-side item pane, btw.

**Comment by yeyun1999** [comment]
1. The built-in PDF preview of Zotero7 is basically unable to see the actual content.
2. Zotero7's search-as-you-type starts searching from the beginning string of the entry, so it should basically not use spaces. If you only use spaces as shortcut keys, it should not affect the search-as-you-type function
3. Quicklook is sometimes used more by me to preview the word and excel files in the attachments, which Zotero cannot directly view

**Comment by windingwind** [comment]
> The built-in PDF preview of Zotero7 is basically unable to see the actual content.

Don't understand and do not agree.

> Zotero7's search-as-you-type starts searching from the beginning string of the entry, so it should basically not use spaces. If you only use spaces as shortcut keys, it should not affect the search-as-you-type function

I'm not very sure about this. The space key is not banned or specially treated by the plugin. You shouldn't expect it to work if it does not.

> Quicklook is sometimes used more by me to preview the word and excel files in the attachments, which Zotero cannot directly view

Zotero is not designed for these formats. I don't think publications would use MS Word/Excel format.

Regarding on the discussion here is not very helpful, I won't pay more attention on this topic. Thanks for the understanding.
