### ISSUE TITLE
[Feature] Add number of annotations as a column?

### ISSUE THREAD

**Issue by MaxVonMustermann** [windingwind/zotero-actions-tags#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Mac OS 15.1
- Zotero Version: 7.0
- Plugin Version: 1.0.0

### Describe the feature request

Can it potentially be achieved to display the number of annotations in a parent file as a column? This would be quite helpful, since there this information has to be looked up manually, by clicking on a parent file and viewing the detailed information pane on the right side.

### Describe the solution you'd like

Self explanatory I guess.

### Anything else?

Thank you in advance! :)

**Comment by windingwind** [comment]
If you know how to write JS, see the [item tree API](https://github.com/zotero/zotero/blob/5bd5bfa343529bd1bee204c81d398c17197623a8/chrome/content/zotero/xpcom/itemTreeManager.js#L130)
