### ISSUE TITLE
[Feature] 高频action停靠在UI界面上

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-actions-tags#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version:  Version: 7.0.5
- Plugin Version:  v2.0.1

### Describe the feature request

目前脚本执行方式：

1. 右键菜单，点击
2. tools菜单，点击
3. 键盘快捷键

但是对于高频脚本，都是不够快捷，
**能否把zotero-tag的一些高频使用的脚本停靠到这里（红色箭头）或者zotero右侧竖向的区域？**

![](https://s3.bmp.ovh/imgs/2024/09/25/5605e1601d44fb24.png)

### Describe the solution you'd like

技术借鉴：

1. 上图粉红色的点是zotero-style插件的列配置，点击一个点，可以切换到对应的列设置，可以参考一下（说明技术上可行）；
2. obsidian有插件可以自定义侧边栏（软件周边）的按钮，参见[PKMer_Obsidian 插件：Commander 添加自定义功能按钮](https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/cmdr/)；
3. 停靠的脚本图标可以使用base64格式的，或者简单的svg源码格式的，存储在脚本的头部区域，这里可以参考油猴脚本的一些规则；

**Comment by windingwind** [comment]
**快捷**键即是最方便的调用方式，快捷方式永远是键盘>鼠标。谢谢建议

**Comment by Geo123abc** [comment]
> **快捷**键即是最方便的调用方式，快捷方式永远是键盘>鼠标。谢谢建议

对于程序员和一些高级用户，确实是 键盘>鼠标，但是使用zotero更多的是非程序员，另外快捷键有时候容易搞混，希望再次考虑一下

**Comment by windingwind** [comment]
对个人来说可能有使用不同习惯，但快捷键比鼠标点击方便应该是一个较广泛的共识。换句话说，如果快捷键没法记住，则说明使用不多，并不是高频功能。（ctrl+c这种真正高频的所有人都记得住）

插入图标对用户界面的完整度具有破坏性，从插件角度我希望尽量避免
