### ISSUE TITLE
[Feature] Add zotero-actions-tags to https://www.zotero.org/support/plugins

### ISSUE THREAD

**Issue by cboulanger** [windingwind/zotero-actions-tags#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

n/A

### Describe the feature request

zotero-actions-tags is missing from https://www.zotero.org/support/plugins

### Describe the solution you'd like

propose to add it.

**Comment by windingwind** [comment]
Please post in the Zotero forums for this request, thank you.
