### ISSUE TITLE
[Bug] failed to add tag with shortcut command+1

### ISSUE THREAD

**Issue by Roger1219** [windingwind/zotero-actions-tags#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  MacOS 15.0.1
- Zotero Version: 7
- Plugin Version: 2.0.4

### Describe the bug

if i set shortcut as 1, it is okay.
If I set shortcut "command,1", restart zotero, press these keys, nothing happened.

### Debug Output

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "TypeError: this[_0x29ca00(...)] is undefined" {file: "jar:file:///Users/roger/Library/Application%20Support/Zotero/Profiles/81l72fru.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 1}]

[JavaScript Error: "连接至服务器时发生错误。请检查网络连接。"]

[JavaScript Error: "连接至服务器时发生错误。请检查网络连接。"]

[JavaScript Error: "连接至服务器时发生错误。请检查网络连接。"]

[JavaScript Error: "连接至服务器时发生错误。请检查网络连接。"]

[JavaScript Error: "连接至服务器时发生错误。请检查网络连接。"]

appName => Zotero, version => 7.0.3 (ARM64), os => macOS 15.0.1, locale => zh-CN, extensions => Zotero IF (1.5.5, extension), Jasminum (1.0.0-16, extension), Zotero Attanger (1.2.6, extension), Ethereal Reference (1.2.3, extension), Ethereal Style (5.1.7, extension), Translate for Zotero (2.0.5, extension), Actions and Tags for Zotero (2.0.4, extension)

**Comment by windingwind** [comment]
Command + number is the shortcut for switching tabs in Zotero. Please use other keys
