### ISSUE TITLE
[Feature] Comprehensive Reference Documentation for Custom Scripts

### ISSUE THREAD

**Issue by liblaf** [windingwind/zotero-actions-tags#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Arch Linux
- Zotero Version: 7.0.11 (64-bit)
- Plugin Version: 2.0.5

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
Yes, I am currently using the Zotero plugin "Actions & Tags" and I am learning how to write custom scripts to automate tasks within Zotero. However, I am struggling to find a comprehensive reference documentation that lists all the variables available for use in scripts, all the global variables that can be required, and their respective methods. For example, I want to automatically add colors to tags when using `item.addTag()`, but I cannot find any documentation on how to do this.

**Why do you need this feature?**
Having a comprehensive reference documentation would greatly enhance the usability and flexibility of the plugin. It would allow users to fully leverage the capabilities of custom scripts without having to guess or search through source code to understand what variables and methods are available. This would save time and improve the overall user experience.

### Describe the solution you'd like

**The solution you'd like**
I would like to see a detailed reference documentation that includes:
- A list of all available variables that can be used in custom scripts.
- A list of all global variables that can be required and their methods.
- Examples of how to use these variables and methods in practical scenarios.

**Alternatives you've considered**
Currently, the only alternative is to search through the source code and experiment with different variables and methods to understand their functionality. This is time-consuming and not very user-friendly.

### Anything else?

Thank you to for creating such a useful plugin! I truly appreciate the effort and time you've put into building this tool. I hope this feature request can help make the plugin even more powerful and accessible for users like me. ❤️

**Comment by windingwind** [comment]
It's impossible to list ALL variables/methods available, as Zotero itself is super complex. The script editor has https://github.com/windingwind/zotero-types configured, so you'll more or less get coding hints for most of the global variables.
